### ISSUE TITLE
Homework 1, Exercise 3 (updated)

### ISSUE THREAD

**Issue by coraallencoleman** [coraallencoleman/stat679ComputingTools#3]
Dear @cecileane,

Thank you for your help with my loop! After applying your suggested change, it worked well.

Here is the commit for my updated code:
https://github.com/coraallencoleman/stat679ComputingTools/commit/5bba7c99f440ba3272d28ca38360977fa8c55d3b

Best,
Cora

**Comment by cecileane** [comment]
Thanks Cora! Please add Melody (@msain) and Yuhui (ywang857) as collaborators, so they can provide feedback on your script, or make your repository public for the time being.

**Comment by ywangflora** [comment]
Hi Cora,

Nice work! In my opinion, you have a clever use of  `sed` and `basename` to grep the useful information.
Additionally, the code is neat and well-organized. 

Here is some suggestions which may improve your coding skills.

Firstly, I think that you code is based on `timetest` files in the log directory. I wonder if it is necessary to involve other log file including `bT1.log`, `net1_snaq.log` and `newtry1.log`. If you want to ignore `bT1`, `net1_snaq` and `newtry1` file, it would be better for you to describe it in the `readme` file.

Then, I really like the code you wrote. But just like the instruction of exercise3, it is better for you to put a comment near each command that uses a regular expression (like sed) because it would be easier for me to read and understand your code.

Finally, it would be better if your csv file does not have spaces after commas. The commas are used to separate the columns, not spaces. In your csv file, spaces become part of the entry values which is not very good.

Thanks for sharing your work. I hope these suggestions are really helpful.

Best,

Yuhui Wang

**Comment by cecileane** [comment]
my mistake Melody (@melpsain): I tagged another github user "msain", who probably had no idea what was going on. I edited my earlier comment in the hope that this other person would stop receiving unwanted emails...

**Comment by melpsain** [comment]
Hi Cora,

I am currently working on getting your code to run on my system because of your use of gsed, and I have been unsuccessful getting gsed to work on my computer. It seems that the code worked well according to Yuhui, so well done!.

I would like to add some commentary on documentation and organization. I think that it was easy to locate each of your files with the information that was provided in your readme file. I think that it may be useful to create sub-directories for your scripts and for the figures that are created using the scripts. Also your script would be more "human readable" if you provided comments on what each of the lines of your script produces. (for example a comment that says that line 7 extracts the name of each of the analysis from the .log files etc.)

Overall I think that you did a great job, and I will be super excited when I am able to get gsed to work on my system.

I hope my suggestions are useful and thank you for letting me view your work.

Melody
