### ISSUE TITLE
Mark homework 2 of Cora-Allen-Coleman

### ISSUE THREAD

**Issue by coraallencoleman** [coraallencoleman/stat679ComputingTools#4]
Dear Professor @cecileane, 

I've linked to my homework 2. I wasn't sure if we're allowed to use the csv module for this exercise. If not, I'd be happy to rewrite the output file section without it. I couldn't find a solution without the csv module tonight, but I can work on it more if you think it would build my skills.

Thank you,
Cora

https://github.com/coraallencoleman/stat679ComputingTools/commit/1b78dec12303a6eacc625e7ebb48654b64435792

**Comment by cecileane** [comment]
no worry: others have used it, and time to rest!

**Comment by cecileane** [comment]
Hi Cora,

Very nice job! and your script worked. More details below.

## overall presentation

It's too bad that you didn't include a section in the readme file to explain how one should run your script. I needed to peek into your code to see that your file `hw2function.py` defined one function, `energytemp()`, and that I should import your file as a module to call that function. It would have been great if I could have run your file as a script from the shell, with arguments for the input file names.

## running your script

I did this to run your script within python:

```python
import hw2function as h
dir = "../../../../coursedata/hw2-datamerge/"
h.energytemp(dir+"waterTemperature.csv", dir+"energy.csv")
quit()
```

and was happy to see that a new file had appeared, `outputfile.csv`:

    #,"Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)",energy
    1,07/29/16 10:26:34 AM,72.86,2.956 warning: this energy value was recorded after the line time
    2,07/29/16 11:26:34 AM,73.92
    3,07/29/16 12:26:34 PM,73.98
    ...
    13,07/29/16 10:26:34 PM,73.27
    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.30
    ...

This output is great, except for the lack of commas at the end of rows that are missing an energy value. The comma is needed to mean that there is another column on the row, with nothing in it (missing value), like this:

    #,"Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)",energy
    1,07/29/16 10:26:34 AM,72.86,2.956 # warning: this energy value was recorded after the line time
    2,07/29/16 11:26:34 AM,73.92,
    3,07/29/16 12:26:34 PM,73.98,
    ...
    13,07/29/16 10:26:34 PM,73.27,
    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.30,
    ...

I like that you included the first energy value, even if it was associated with the previous day. I also like the warning! In the output above, I added a # sign, because some software that read csv files (like R) would be able to ignore the warning and would understand that the cell has a number only.

## about your code

Your code is sleak, that's very nice. It could use more comments!

You made great use of `assert` statements to check assumptions, return errors when appropriate, like to make sure that you don't overwrite existing files.

Very nice use of regular expressions!

On line 20 the last line of the energy file is excluded, but there aren't any comments to explain why (total line) and you don't check this assumption.

`pass` statements can typically be replaced by more elegant code. For example, you have this on lines 33-36:

```python
for i in energy:
    if (energy.index(i) == 0) or (energy.index(i) == len(energy) - 1):
        pass
    else:
        xxx
```

Another option would have been a `continue` statement, to avoid the `else` block and one level of indentation for this block:

```python
for i in energy:
    if (energy.index(i) == 0) or (energy.index(i) == len(energy) - 1):
        continue
    xxx
```

Finally, you could have broken your work into separate smaller functions.
